[type]
delim = ","
quote = "\""
escape = "\""
header = true
ignore_errors = true

[columns]
"代码" = "string"
"名称" = "string"
"交易日期" = "string"  # 或者根据需要转换为日期类型
"前收盘价"= "float"
"开盘价" = "float"
"最高价" = "float"
"最低价" = "float"
"收盘价" = "float"
"涨跌" = "float"
"涨跌幅(%)" = "float"
"已计息天数" = "float"
"应计利息" = "float"
"剩余期限(年)" = "float"
"当期收益率(%)" = "float"
"纯债到期收益率(%)" = "float"
"纯债价值" = "float"
"纯债溢价" = "float"
"纯债溢价率(%)" = "float"
"转股价格" = "float"
"转股比例" = "float"
"转换价值" = "float"
"转股溢价" = "float"
"转股溢价率(%)" = "float"
"转股市盈率" = "float"
"转股市净率" = "float"
"套利空间" = "float"
"平价/底价" = "float"
"期限(年)" = "float"
"发行日期" = "string"
"票面利率/发行参考利率(%)" = "float"
"交易市场" = "string"
"债券类型" = "string"
"债券最新评级" = "string"
"债券余额" = "float"